name: Test Discord Notification

on:
  workflow_dispatch:

jobs:
  test-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Webhook Message
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "GitHub Test Notifier",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "✅ Test - ${{ github.event.inputs.event_type }}",
                "description": "This is a test message for event type: `${{ github.event.inputs.event_type }}`.",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Triggered by",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  }
                ]
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK }}